@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Initial POS system with Auto-Update and Virtual Keyboard"
echo Setting branch to main...
git branch -M main
echo Adding remote origin...
git remote remove origin >nul 2>&1
git remote add origin https://github.com/siyabill/restaurantpos.git
echo Pushing to GitHub...
git push -u origin main
echo Done! Now you can publish the release on GitHub.
pause
